const STORAGE_KEY='smartMoneyMonthlyV2';
const THEME_KEY='smartMoneyTheme';
const APP_VERSION='0.2.0';
const defaultState={currentBalance:0,salary:0,currentSavings:0,targetBalance:1000,actualSaving:null,expenses:[],history:[],notificationLog:{}};
const clone=o=>JSON.parse(JSON.stringify(o));
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(Number(v)||0);
const round=v=>Math.round((Number(v)||0)*100)/100;
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function targetMonthDate(){const d=new Date();d.setMonth(d.getMonth()+1,1);return d}
function targetMonthKey(){return monthKey(targetMonthDate())}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return clone(defaultState);if(saved.targetBalance==null){saved.targetBalance=round(saved.reserve||0);delete saved.reserve}if(saved.currentSavings==null)saved.currentSavings=0;if(saved.actualSaving===undefined)saved.actualSaving=null;if(!Array.isArray(saved.history))saved.history=[];if(!saved.notificationLog)saved.notificationLog={};saved.expenses=(saved.expenses||[]).map(e=>({...e,recurring:Boolean(e.recurring),day:e.day?Number(e.day):null}));return {...clone(defaultState),...saved}}catch{return clone(defaultState)}}
let state=load();let editingId=null;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function totals(){const by={credit:0,debit:0,bank:0};let recurring=0;state.expenses.forEach(e=>{by[e.method]=round(by[e.method]+e.amount);if(e.recurring)recurring=round(recurring+e.amount)});const expenses=round(by.credit+by.debit+by.bank);const available=round(state.currentBalance+state.salary);const keepBeforeExpenses=round(expenses+state.targetBalance);const recommended=round(Math.max(0,available-keepBeforeExpenses));const shortage=round(Math.max(0,keepBeforeExpenses-available));const effectiveSaving=state.actualSaving==null?recommended:round(state.actualSaving);const projectedSavings=round(state.currentSavings+effectiveSaving);const finalBank=round(available-expenses-effectiveSaving);return{by,expenses,available,keepBeforeExpenses,recommended,shortage,recurring,effectiveSaving,projectedSavings,finalBank}}
function syncInputs(){state.currentBalance=round($('currentBalance').value);state.salary=round($('salary').value);state.currentSavings=round($('currentSavings').value);state.targetBalance=round($('targetBalance').value);const raw=$('actualSaving').value.trim();state.actualSaving=raw===''?null:round(raw);save();renderSummary()}
function renderSummary(){const t=totals();$('currentSavingsTotal').textContent=money(state.currentSavings);$('projectedSavingsTotal').textContent=money(t.projectedSavings);$('availableTotal').textContent=money(t.available);$('expensesTotal').textContent=money(t.expenses);$('recommendedSavingTotal').textContent=money(t.recommended);$('actualSavingTotal').textContent=money(t.effectiveSaving);$('savingResult').textContent=money(t.recommended);const hero=$('heroCard'),status=$('planStatus');hero.classList.remove('hero-good','hero-warn');let msg='';if(t.shortage>0){msg=`חסרים ${money(t.shortage)} כדי לכסות את כל ההוצאות ועדיין להישאר עם ${money(state.targetBalance)} בעו״ש.`;hero.classList.add('hero-warn');status.textContent='חסר כסף'}else{msg=`המלצה: ${money(t.recommended)} לחיסכון. אם תעביר ${money(t.effectiveSaving)}, אחרי ההוצאות צפויים להישאר ${money(t.finalBank)} בעו״ש.`;hero.classList.add(t.finalBank>=state.targetBalance?'hero-good':'hero-warn');status.textContent=t.finalBank>=state.targetBalance?'התכנון מאוזן':'מתחת ליעד'}$('savingMessage').textContent=msg;const diff=round(t.effectiveSaving-t.recommended);$('actualSavingHint').textContent=state.actualSaving==null?'לא הוגדר סכום בפועל — החישוב משתמש כרגע בסכום המומלץ.':diff===0?'הסכום בפועל זהה להמלצה.':diff>0?`אתה מתכנן לחסוך ${money(diff)} יותר מההמלצה.`:`אתה מתכנן לחסוך ${money(Math.abs(diff))} פחות מההמלצה.`;$('creditTotal').textContent=money(t.by.credit);$('debitTotal').textContent=money(t.by.debit);$('bankTotal').textContent=money(t.by.bank);$('recurringTotalText').textContent=t.recurring>0?`מתוך ההוצאות, ${money(t.recurring)} הן הוצאות קבועות שחוזרות כל חודש.`:'אין כרגע הוצאות קבועות חודשיות.'}
function methodName(m){return m==='credit'?'אשראי':m==='debit'?'Debit':'עו״ש'}
function renderExpenses(){const box=$('expenseList');if(!state.expenses.length){box.innerHTML='<div class="empty">עדיין לא הוספת הוצאות לחודש הבא.</div>'}else{box.innerHTML=state.expenses.map(e=>`<div class="expense-row"><div><strong>${escapeHtml(e.name)}</strong><small><span class="mini-badge">${methodName(e.method)}</span>${e.day?`<span class="mini-badge">יורד ב-${e.day}</span>`:''}${e.recurring?'<span class="mini-badge recurring">קבוע כל חודש</span>':''}</small></div><div class="expense-side"><strong>${money(e.amount)}</strong><button type="button" data-edit="${e.id}" aria-label="עריכה">✎</button><button type="button" data-delete="${e.id}" aria-label="מחיקה">×</button></div></div>`).join('');box.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{state.expenses=state.expenses.filter(e=>e.id!==b.dataset.delete);save();render()}));box.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>startEdit(b.dataset.edit)))}renderSummary();renderUpcoming()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function clearExpenseForm(){$('expenseName').value='';$('expenseAmount').value='';$('expenseMethod').value='credit';$('expenseDay').value='';$('expenseRecurring').checked=false;editingId=null;$('saveExpenseBtn').textContent='הוסף הוצאה';$('cancelEditBtn').classList.add('hidden')}
function startEdit(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;editingId=id;$('expenseName').value=e.name;$('expenseAmount').value=e.amount;$('expenseMethod').value=e.method;$('expenseDay').value=e.day||'';$('expenseRecurring').checked=e.recurring;$('saveExpenseBtn').textContent='שמור שינויים';$('cancelEditBtn').classList.remove('hidden');$('expenseName').focus()}
function saveExpense(){const name=$('expenseName').value.trim();const amount=round($('expenseAmount').value);const method=$('expenseMethod').value;const recurring=$('expenseRecurring').checked;const dayRaw=Number($('expenseDay').value);const day=dayRaw>=1&&dayRaw<=31?Math.trunc(dayRaw):null;if(!name){alert('רשום שם להוצאה');return}if(amount<=0){alert('רשום סכום גדול מ-0');return}if($('expenseDay').value&&day===null){alert('יום החיוב חייב להיות בין 1 ל-31');return}if(editingId){const i=state.expenses.findIndex(e=>e.id===editingId);if(i>=0)state.expenses[i]={...state.expenses[i],name,amount,method,recurring,day}}else state.expenses.push({id:String(Date.now()),name,amount,method,recurring,day});clearExpenseForm();save();render()}
function setMonthTitle(){const d=targetMonthDate();$('monthTitle').textContent=`תכנון ${new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(d)}`}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);$('themeBtn').textContent=theme==='dark'?'☀️':'🌙';$('themeColorMeta').setAttribute('content',theme==='dark'?'#0b1220':'#111827')}
function initTheme(){const saved=localStorage.getItem(THEME_KEY);applyTheme(saved||(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))}
function newMonth(){const t=totals();if(!confirm('לסגור את התכנון הנוכחי ולפתוח חודש חדש?\n\nהוצאות חד-פעמיות יימחקו, והוצאות קבועות יישארו.'))return;state.history.unshift({id:'m_'+Date.now(),month:targetMonthKey(),salary:state.salary,currentBalance:state.currentBalance,currentSavings:state.currentSavings,targetBalance:state.targetBalance,expenses:clone(state.expenses),expenseTotal:t.expenses,recommendedSaving:t.recommended,actualSaving:t.effectiveSaving,finalBank:t.finalBank,projectedSavings:t.projectedSavings,closedAt:new Date().toISOString()});state.currentSavings=t.projectedSavings;state.currentBalance=t.finalBank;state.salary=0;state.actualSaving=null;state.expenses=state.expenses.filter(e=>e.recurring);save();render();alert('החודש נשמר בהיסטוריה והוצאות קבועות הועברו לחודש הבא.')}
function renderHistory(){const box=$('historyList');if(!state.history.length){box.innerHTML='<div class="empty">עדיין אין חודשים סגורים.</div>';return}box.innerHTML=state.history.map(h=>`<details class="history-item"><summary><span>${formatMonth(h.month)}</span><strong>${money(h.actualSaving)} חיסכון</strong></summary><div class="history-details"><span>הכנסה: ${money(h.salary)}</span><span>הוצאות: ${money(h.expenseTotal)}</span><span>המלצה: ${money(h.recommendedSaving)}</span><span>נשאר בעו״ש: ${money(h.finalBank)}</span><span>חיסכון בסוף: ${money(h.projectedSavings)}</span></div></details>`).join('')}
function formatMonth(key){const [y,m]=key.split('-').map(Number);return new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function exportBackup(){const payload={app:'Smart Money',version:APP_VERSION,exportedAt:new Date().toISOString(),state,theme:localStorage.getItem(THEME_KEY)||'light'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`smart-money-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data||!data.state)throw new Error();if(!confirm('לשחזר את הגיבוי? הנתונים הנוכחיים יוחלפו.'))return;state={...clone(defaultState),...data.state};state.expenses=(state.expenses||[]).map(e=>({...e,recurring:Boolean(e.recurring),day:e.day?Number(e.day):null}));save();if(data.theme)applyTheme(data.theme);render();alert('הגיבוי שוחזר בהצלחה.')}catch{alert('קובץ הגיבוי אינו תקין.')}};r.readAsText(file)}
function dueDateForExpense(e){if(!e.day)return null;const d=targetMonthDate();const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return new Date(d.getFullYear(),d.getMonth(),Math.min(e.day,last),12,0,0)}
function daysFromToday(date){const a=new Date();a.setHours(0,0,0,0);const b=new Date(date);b.setHours(0,0,0,0);return Math.ceil((b-a)/86400000)}
function upcoming(){return state.expenses.filter(e=>e.day).map(e=>({...e,due:dueDateForExpense(e)})).sort((a,b)=>a.due-b.due)}
function renderUpcoming(){const items=upcoming();const box=$('upcomingList');if(!items.length){box.innerHTML='<div class="empty">הוסף יום חיוב להוצאה כדי לראות מה יורד בקרוב.</div>';return}box.innerHTML=items.slice(0,6).map(e=>{const days=daysFromToday(e.due);const when=days<0?'עבר':days===0?'היום':days===1?'מחר':`בעוד ${days} ימים`;return `<div class="upcoming-row"><div><strong>${escapeHtml(e.name)}</strong><small>${when} · ${methodName(e.method)}</small></div><strong>${money(e.amount)}</strong></div>`}).join('')}
async function requestNotifications(){if(!('Notification'in window)){alert('הדפדפן הזה לא תומך בהתראות Web.');return}const p=await Notification.requestPermission();$('notificationBtn').textContent=p==='granted'?'התראות פעילות':'אפשר התראות';if(p==='granted'){checkNotifications(true)}else alert('לא ניתנה הרשאה להתראות.')}
async function notify(title,body,tag){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'./icon-192.png',badge:'./icon-192.png',tag})}catch{new Notification(title,{body,icon:'./icon-192.png',tag})}}
function checkNotifications(force=false){if(!('Notification'in window)||Notification.permission!=='granted')return;upcoming().forEach(e=>{const days=daysFromToday(e.due);if(days>=0&&days<=3){const tag=`expense-${targetMonthKey()}-${e.id}-${days}`;if(force||!state.notificationLog[tag]){notify('Smart Money',`${e.name} — ${money(e.amount)} ${days===0?'יורד היום':days===1?'יורד מחר':`יורד בעוד ${days} ימים`}`,tag);state.notificationLog[tag]=Date.now()}}});save()}
function showVersion(){alert(`Smart Money v${APP_VERSION}\n\nנוסף: חודש חדש, עריכת הוצאות, ימי חיוב, היסטוריה, חיסכון בפועל, גיבוי ושחזור והתראות מקומיות.`)}
function render(){$('currentBalance').value=state.currentBalance||'';$('salary').value=state.salary||'';$('currentSavings').value=state.currentSavings||'';$('targetBalance').value=state.targetBalance;$('actualSaving').value=state.actualSaving==null?'':state.actualSaving;$('versionBtn').textContent=`v${APP_VERSION}`;$('notificationBtn').textContent=('Notification'in window&&Notification.permission==='granted')?'התראות פעילות':'אפשר התראות';renderExpenses();renderHistory();renderUpcoming()}
['currentBalance','salary','currentSavings','targetBalance','actualSaving'].forEach(id=>$(id).addEventListener('input',syncInputs));$('saveExpenseBtn').addEventListener('click',saveExpense);$('cancelEditBtn').addEventListener('click',clearExpenseForm);$('addExpenseBtn').addEventListener('click',()=>{$('expenseName').focus()});$('expenseAmount').addEventListener('keydown',e=>{if(e.key==='Enter')saveExpense()});$('themeBtn').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));$('versionBtn').addEventListener('click',showVersion);$('newMonthBtn').addEventListener('click',newMonth);$('exportBtn').addEventListener('click',exportBackup);$('importBtn').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value=''});$('notificationBtn').addEventListener('click',requestNotifications);$('resetBtn').addEventListener('click',()=>{if(confirm('למחוק את כל נתוני התכנון, ההיסטוריה וההגדרות מהמכשיר?')){state=clone(defaultState);save();render()}});
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(()=>checkNotifications()).catch(()=>{}))}document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkNotifications()});window.addEventListener('focus',()=>checkNotifications());initTheme();setMonthTitle();render();