const STORAGE_KEY='smartMoneyMonthlyV2';
const defaultState={currentBalance:0,salary:0,targetBalance:1000,expenses:[]};
const clone=o=>JSON.parse(JSON.stringify(o));
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(Number(v)||0);
const round=v=>Math.round((Number(v)||0)*100)/100;
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return clone(defaultState);if(saved.targetBalance==null){saved.targetBalance=round(saved.reserve||0);delete saved.reserve}return saved}catch{return clone(defaultState)}}
let state=load();
state.expenses=(state.expenses||[]).map(e=>({...e,recurring:Boolean(e.recurring)}));
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function totals(){const by={credit:0,debit:0,bank:0};let recurring=0;state.expenses.forEach(e=>{by[e.method]=round(by[e.method]+e.amount);if(e.recurring)recurring=round(recurring+e.amount)});const expenses=round(by.credit+by.debit+by.bank);const available=round(state.currentBalance+state.salary);const keepBeforeExpenses=round(expenses+state.targetBalance);const saving=round(Math.max(0,available-keepBeforeExpenses));const shortage=round(Math.max(0,keepBeforeExpenses-available));return{by,expenses,available,keepBeforeExpenses,saving,shortage,recurring}}
function syncInputs(){state.currentBalance=round($('currentBalance').value);state.salary=round($('salary').value);state.targetBalance=round($('targetBalance').value);save();renderSummary()}
function renderSummary(){const t=totals();$('availableTotal').textContent=money(t.available);$('expensesTotal').textContent=money(t.expenses);$('keepTotal').textContent=money(t.keepBeforeExpenses);$('targetBalanceTotal').textContent=money(state.targetBalance);$('savingResult').textContent=money(t.saving);if(t.shortage>0){$('savingMessage').textContent=`חסרים ${money(t.shortage)} כדי לכסות את ההוצאות ועדיין להישאר עם ${money(state.targetBalance)} בעו״ש.`;$('savingResult').classList.add('negative')}else{$('savingMessage').textContent=t.saving>0?`אפשר להעביר ${money(t.saving)} לחיסכון, ואחרי כל ההוצאות יישארו ${money(state.targetBalance)} בעו״ש.`:`כדי להישאר עם ${money(state.targetBalance)} בעו״ש אחרי ההוצאות, לא מומלץ להעביר כרגע כסף לחיסכון.`;$('savingResult').classList.remove('negative')}$('creditTotal').textContent=money(t.by.credit);$('debitTotal').textContent=money(t.by.debit);$('bankTotal').textContent=money(t.by.bank);$('recurringTotalText').textContent=t.recurring>0?`מתוך ההוצאות, ${money(t.recurring)} הן הוצאות קבועות שחוזרות כל חודש.`:'אין כרגע הוצאות קבועות חודשיות.'}
function methodName(m){return m==='credit'?'אשראי':m==='debit'?'Debit':'עו״ש'}
function renderExpenses(){const box=$('expenseList');if(!state.expenses.length){box.innerHTML='<div class="empty">עדיין לא הוספת הוצאות לחודש הבא.</div>'}else{box.innerHTML=state.expenses.map(e=>`<div class="expense-row"><div><strong>${escapeHtml(e.name)}</strong><small>${methodName(e.method)}${e.recurring?' · קבוע כל חודש':''}</small></div><div class="expense-side"><strong>${money(e.amount)}</strong><button type="button" data-delete="${e.id}" aria-label="מחיקה">×</button></div></div>`).join('');box.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{state.expenses=state.expenses.filter(e=>e.id!==b.dataset.delete);save();render()}))}renderSummary()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addExpense(){const name=$('expenseName').value.trim();const amount=round($('expenseAmount').value);const method=$('expenseMethod').value;const recurring=$('expenseRecurring').checked;if(!name){alert('רשום שם להוצאה');return}if(amount<=0){alert('רשום סכום גדול מ-0');return}state.expenses.push({id:String(Date.now()),name,amount,method,recurring});$('expenseName').value='';$('expenseAmount').value='';$('expenseRecurring').checked=false;save();render()}
function render(){$('currentBalance').value=state.currentBalance||'';$('salary').value=state.salary||'';$('targetBalance').value=state.targetBalance;renderExpenses()}
['currentBalance','salary','targetBalance'].forEach(id=>$(id).addEventListener('input',syncInputs));$('saveExpenseBtn').addEventListener('click',addExpense);$('addExpenseBtn').addEventListener('click',()=>$('expenseName').focus());$('expenseAmount').addEventListener('keydown',e=>{if(e.key==='Enter')addExpense()});$('resetBtn').addEventListener('click',()=>{if(confirm('למחוק את כל נתוני התכנון מהמכשיר?')){state=clone(defaultState);save();render()}});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}render();