(()=>{
const SHIFT_KEY='ilShiftTrackerData_v1';
const ACTUAL_KEY='smartMoneyActualSalaryReceivedV1';
const PAYDAY_KEY='smartMoneySalaryPayDayV1';
const NI_THRESHOLD=7703,NI_CEILING=51910,NI_RATE_LOW=0.0427,NI_RATE_HIGH=0.1217;
const round=v=>Math.round((Number(v)||0)*100)/100;
const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(Number(v)||0);
function monthKey(ms=Date.now()){const d=new Date(ms);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function previousMonthKey(){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return monthKey(d.getTime())}
function deduction(grossWork){const low=Math.min(grossWork,NI_THRESHOLD),high=Math.max(0,Math.min(grossWork,NI_CEILING)-NI_THRESHOLD);return low*NI_RATE_LOW+high*NI_RATE_HIGH}
function getPayDay(){const n=Number(localStorage.getItem(PAYDAY_KEY));return Number.isInteger(n)&&n>=1&&n<=31?n:null}
function setPayDay(v){const n=Number(v);if(Number.isInteger(n)&&n>=1&&n<=31)localStorage.setItem(PAYDAY_KEY,String(n));else localStorage.removeItem(PAYDAY_KEY)}
function salaryPeriod(){const day=getPayDay(),today=new Date().getDate();if(day&&today<day)return{month:previousMonthKey(),waiting:true,day};if(day&&today>=day)return{month:previousMonthKey(),waiting:false,day};return{month:monthKey(),waiting:true,day:null}}
function getShiftSalary(targetMonth){try{const raw=localStorage.getItem(SHIFT_KEY);if(!raw)return null;const s=JSON.parse(raw);const shifts=Array.isArray(s.shifts)?s.shifts:[];const month=shifts.filter(x=>monthKey(Number(x.start))===targetMonth);if(!month.length)return null;const totalWork=month.reduce((a,x)=>a+(Number(x.pay)||0),0);const travel=month.reduce((a,x)=>a+(Number(x.travel)||0),0);const expenses=month.reduce((a,x)=>a+(Number(x.expenses)||0),0);const net=round(totalWork-deduction(totalWork)+travel-expenses);return{net,count:month.length,month:targetMonth}}catch(e){console.warn('Shift Clock sync failed',e);return null}}
function getActual(periodMonth){try{const raw=localStorage.getItem(ACTUAL_KEY);if(!raw)return null;const data=JSON.parse(raw);if(data.periodMonth!==periodMonth)return null;const amount=Number(data.amount);return Number.isFinite(amount)&&amount>=0?round(amount):null}catch{return null}}
function setActual(amount,periodMonth){if(amount==null){localStorage.removeItem(ACTUAL_KEY);return}localStorage.setItem(ACTUAL_KEY,JSON.stringify({periodMonth,amount:round(amount),savedAt:new Date().toISOString()}))}
function applyEffective(value){const salary=document.getElementById('salary');if(!salary)return;const next=String(round(value||0));if(salary.value!==next){salary.value=next;salary.dispatchEvent(new Event('input',{bubbles:true}));salary.dispatchEvent(new Event('change',{bubbles:true}))}}
function sync(){const expectedInput=document.getElementById('expectedSalary'),actualInput=document.getElementById('actualSalaryReceived'),payDayInput=document.getElementById('salaryPayDay'),syncStatus=document.getElementById('salarySyncStatus'),actualStatus=document.getElementById('actualSalaryStatus'),clearBtn=document.getElementById('clearActualSalary');const period=salaryPeriod(),data=getShiftSalary(period.month),actual=getActual(period.month);if(payDayInput&&document.activeElement!==payDayInput)payDayInput.value=getPayDay()||'';if(period.day&&period.waiting){if(expectedInput)expectedInput.value=data?String(data.net):'';if(syncStatus)syncStatus.textContent=data?`משכורת צפויה עבור ${period.month} · ${data.count} משמרות · ${money(data.net)} · תישאר עד ה-${period.day} בחודש`:`לא נמצאו נתוני משמרות עבור ${period.month}.`;if(actual!=null){applyEffective(actual);if(actualStatus)actualStatus.textContent=`כבר הוזנה משכורת בפועל: ${money(actual)}.`}else if(data){applyEffective(data.net);if(actualStatus)actualStatus.textContent=`עד ה-${period.day} החישובים משתמשים במשכורת הצפויה.`}else applyEffective(0)}else if(period.day){if(expectedInput)expectedInput.value='';if(syncStatus)syncStatus.textContent=`הגיע יום המשכורת (${period.day} בחודש) — המשכורת הצפויה הוסרה. הזן את הסכום שקיבלת בפועל.`;if(actual!=null){applyEffective(actual);if(actualStatus)actualStatus.textContent=`החישובים משתמשים במשכורת בפועל: ${money(actual)}.`}else{applyEffective(0);if(actualStatus)actualStatus.textContent='הזן את המשכורת שקיבלת בפועל.'}}else{if(expectedInput)expectedInput.value=data?String(data.net):'';if(syncStatus)syncStatus.textContent='בחר יום קבוע לקבלת המשכורת כדי שהאפליקציה תדע מתי להחליף בין צפויה לבפועל.';if(actual!=null)applyEffective(actual);else if(data)applyEffective(data.net)}if(actualInput&&document.activeElement!==actualInput)actualInput.value=actual==null?'':String(actual);if(clearBtn)clearBtn.style.display=actual==null?'none':'inline-flex'}
function bind(){const actualInput=document.getElementById('actualSalaryReceived'),payDayInput=document.getElementById('salaryPayDay'),clearBtn=document.getElementById('clearActualSalary');if(payDayInput&&!payDayInput.dataset.bound){payDayInput.dataset.bound='1';payDayInput.addEventListener('change',()=>{setPayDay(payDayInput.value);sync()})}if(actualInput&&!actualInput.dataset.bound){actualInput.dataset.bound='1';actualInput.addEventListener('change',()=>{const raw=actualInput.value.trim(),period=salaryPeriod();if(raw===''){setActual(null,period.month);sync();return}const amount=Number(raw);if(!Number.isFinite(amount)||amount<0)return;setActual(amount,period.month);sync()})}if(clearBtn&&!clearBtn.dataset.bound){clearBtn.dataset.bound='1';clearBtn.addEventListener('click',()=>{setActual(null,salaryPeriod().month);if(actualInput)actualInput.value='';sync()})}}
function run(){bind();sync()}
document.addEventListener('DOMContentLoaded',()=>setTimeout(run,180));window.addEventListener('load',()=>setTimeout(run,260));window.addEventListener('focus',sync);window.addEventListener('pageshow',sync);window.addEventListener('storage',e=>{if([SHIFT_KEY,ACTUAL_KEY,PAYDAY_KEY].includes(e.key))sync()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});
})();