(()=>{
const SHIFT_KEY='ilShiftTrackerData_v1';
const ACTUAL_KEY='smartMoneyActualSalaryReceivedV1';
const NI_THRESHOLD=7703,NI_CEILING=51910,NI_RATE_LOW=0.0427,NI_RATE_HIGH=0.1217;
const round=v=>Math.round((Number(v)||0)*100)/100;
const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(Number(v)||0);
function monthKey(ms=Date.now()){const d=new Date(ms);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function deduction(grossWork){const low=Math.min(grossWork,NI_THRESHOLD),high=Math.max(0,Math.min(grossWork,NI_CEILING)-NI_THRESHOLD);return low*NI_RATE_LOW+high*NI_RATE_HIGH}
function getShiftSalary(){try{const raw=localStorage.getItem(SHIFT_KEY);if(!raw)return null;const s=JSON.parse(raw);const shifts=Array.isArray(s.shifts)?s.shifts:[];const current=monthKey();const month=shifts.filter(x=>monthKey(Number(x.start))===current);const totalWork=month.reduce((a,x)=>a+(Number(x.pay)||0),0);const travel=month.reduce((a,x)=>a+(Number(x.travel)||0),0);const expenses=month.reduce((a,x)=>a+(Number(x.expenses)||0),0);const net=round(totalWork-deduction(totalWork)+travel-expenses);return{net,count:month.length,current}}catch(e){console.warn('Shift Clock sync failed',e);return null}}
function getActual(){try{const raw=localStorage.getItem(ACTUAL_KEY);if(!raw)return null;const data=JSON.parse(raw);if(data.month!==monthKey())return null;const amount=Number(data.amount);return Number.isFinite(amount)&&amount>=0?round(amount):null}catch{return null}}
function setActual(amount){if(amount==null){localStorage.removeItem(ACTUAL_KEY);return}localStorage.setItem(ACTUAL_KEY,JSON.stringify({month:monthKey(),amount:round(amount),savedAt:new Date().toISOString()}))}
function applyEffective(value){const salary=document.getElementById('salary');if(!salary)return;const next=String(round(value||0));if(salary.value!==next){salary.value=next;salary.dispatchEvent(new Event('input',{bubbles:true}));salary.dispatchEvent(new Event('change',{bubbles:true}))}}
function sync(){const expectedInput=document.getElementById('expectedSalary'),actualInput=document.getElementById('actualSalaryReceived'),syncStatus=document.getElementById('salarySyncStatus'),actualStatus=document.getElementById('actualSalaryStatus'),clearBtn=document.getElementById('clearActualSalary');const data=getShiftSalary(),actual=getActual();if(expectedInput)expectedInput.value=data?String(data.net):'';if(syncStatus)syncStatus.textContent=data?`מסונכרן משעון הנוכחות · ${data.count} משמרות · ${money(data.net)} נטו משוער`:'לא נמצאו כרגע נתוני שעון נוכחות לחודש הזה.';if(actualInput&&document.activeElement!==actualInput)actualInput.value=actual==null?'':String(actual);if(clearBtn)clearBtn.style.display=actual==null?'none':'inline-flex';if(actual!=null){applyEffective(actual);if(actualStatus)actualStatus.textContent=`החישובים משתמשים במשכורת בפועל: ${money(actual)}.`}else if(data){applyEffective(data.net);if(actualStatus)actualStatus.textContent='עדיין לא הוזנה משכורת בפועל — החישובים משתמשים בסכום המשוער מאפליקציית השעות.'}else{if(actualStatus)actualStatus.textContent='אפשר להזין כאן את הסכום שקיבלת בפועל.'}}
function bind(){const actualInput=document.getElementById('actualSalaryReceived'),clearBtn=document.getElementById('clearActualSalary');if(actualInput&&!actualInput.dataset.bound){actualInput.dataset.bound='1';actualInput.addEventListener('change',()=>{const raw=actualInput.value.trim();if(raw===''){setActual(null);sync();return}const amount=Number(raw);if(!Number.isFinite(amount)||amount<0)return;setActual(amount);sync()})}if(clearBtn&&!clearBtn.dataset.bound){clearBtn.dataset.bound='1';clearBtn.addEventListener('click',()=>{setActual(null);if(actualInput)actualInput.value='';sync()})}}
function run(){bind();sync()}
document.addEventListener('DOMContentLoaded',()=>setTimeout(run,180));window.addEventListener('load',()=>setTimeout(run,260));window.addEventListener('focus',sync);window.addEventListener('pageshow',sync);window.addEventListener('storage',e=>{if(e.key===SHIFT_KEY||e.key===ACTUAL_KEY)sync()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});
})();